#!/bin/bash
# copy the current config.ini file to the server.ini folder
BASE_FILE=${1:-config.ini}
CONFIG_LOCATION="${PWD}/${BASE_FILE}"
case "$(uname -s)" in

   Darwin)
     cp $CONFIG_LOCATION /usr/local/etc/hhvm/server.ini
     echo 'Your default server.ini has been updated'
     ;;

   Linux)
     cp $CONFIG_LOCATION /etc/hhvm/server.ini
     echo 'Your default server.ini has been updated'
     ;;

   *)
     echo 'Your OS is not supported.'
     ;;
esac
